---
# Install the newest NASM Assember

- name: Set gcc module call
  set_fact:
    nasm_install_dir: "{{ '/usr/local' if is_admin else '{{ install_dir }}' }}"


- name: create compilation dir
  file:
    path: "{{ compile_dir }}"
    state: directory

- name: create installation dir
  become: "{{ is_admin }}"
  file:
    path: "{{ nasm_install_dir }}"
    state: directory

- name: get nasm
  # should use get_url or even unpack directly. Workaround missing SNI support in Taito's python 2.6
  command: wget "https://www.zytor.com/pub/nasm/releasebuilds/{{ nasm_version }}/nasm-{{ nasm_version }}.tar.xz"
  args:
    chdir: "{{ compile_dir }}"
    creates: "nasm-{{ nasm_version }}.tar.xz"

- name: unpack nasm
  unarchive:
    remote_src: yes
    src: "{{ compile_dir }}/nasm-{{ nasm_version }}.tar.xz"
    dest: "{{ compile_dir }}"

- name: compile nasm
  command: "{{ item }}"
  args:
    chdir: "{{ compile_dir }}/nasm-{{ nasm_version }}" 
  with_items:
    - ./configure --prefix={{ nasm_install_dir }}
    - make -j5

- name: install nasm
  command: "{{ item }}"
  become: "{{ is_admin }}"
  args:
    chdir: "{{ compile_dir }}/nasm-{{ nasm_version }}" 
    creates: "{{ nasm_install_dir }}/bin/nasm"
  with_items:
    - make install
    
    
- name: Fix permissions (if shared group is set)
  file:
    path={{ nasm_install_dir }}
    group={{ shared_group }}
    mode="g+rwX,o+rX"
    recurse=yes
  when: shared_group is defined