---
# tasks file for tsv-tools

- name: Setup directories
  become: no
  file:
    path: "{{ item }}"
    mode: 0777
    recurse: yes
    state: directory
  loop:
    -  "{{ src_root }}"
    -  "{{ install_dir }}/bin/"

- name: Get source
  unarchive:
    src: "{{ release_url }}"
    dest: "{{ src_root }}"
    remote_src: yes

- name: Copy binaries to install_dir
  copy:
    remote_src: true
    src: "{{ compile_dir }}/bin/{{ item }}"
    dest: "{{ install_dir }}/bin/{{ item }}"
    mode: 0755
  loop:
    - csv2tsv
    - number-lines
    - tsv-filter
    - tsv-pretty
    - tsv-select
    - tsv-summarize
    - keep-header
    - tsv-append
    - tsv-join
    - tsv-sample
    - tsv-split
    - tsv-uniq


- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX"
    recurse: yes
  when: shared_group is defined
