---
galaxy_info:
  author: Stefan Hageneder
  description: Compiles and installs ffmpeg with configurable versions and features like x265, x264, opus, fdk-aac, vpx.
  company: your company (optional)
  license: GPLv2
  min_ansible_version: 1.7
  galaxy_tags:
    - ffmpeg
    - multimedia
  platforms:
    - name: Ubuntu
      versions:
        - all

    - name: Debian
      versions:
        - all

dependencies: []
  
