---
# defaults

package_name: tsv-utils
version: "{{ tsv_tools_version }}"
name_suffix: "osx-x86_64_ldc2"
release_url: "https://github.com/eBay/tsv-utils/releases/download/v{{ version }}/tsv-utils-v{{ version }}_{{ name_suffix }}.tar.gz"
src_root: "{{ compile_root }}"
compile_dir: "{{ src_root }}/{{ package_name }}-v{{ version }}_{{ name_suffix }}"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"
module_path: "{{ module_root }}/{{ package_name }}"
